services:
  asset-metadata:
    image: dacm.assetmetadataservice
    build:
      context: .
      dockerfile: AssetMetadataService/src/DACM.AssetMetadataService/Dockerfile
      
  briefing-metadata:
    image: dacm.briefingmetadataservice
    build:
      context: .
      dockerfile: BriefingMetadataService/src/DACM.BriefingMetadataService/Dockerfile
    
  content-distribution-backend:
    image: dacm.contentdistributionbackend
    build:
      context: .
      dockerfile: ContentDistributionBackend/src/DACM.ContentDistribution/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - asset-metadata
      - briefing-metadata
      - redis

  redis:
    image: redis
