/*
 * AssetMetadataService
 *
 * Service providing asset metadata
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using DACM.AssetMetadataService.Attributes;

using Microsoft.AspNetCore.Authorization;
using DACM.AssetMetadataService.Models;

namespace DACM.AssetMetadataService.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DefaultApiController : ControllerBase
    { 
        /// <summary>
        /// Responds with asset metadata for requested asset IDs
        /// </summary>
        /// <remarks>Responds with asset metadata for requested asset IDs</remarks>
        /// <param name="body">Asset IDs</param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Invalid input</response>
        /// <response code="422">Validation exception</response>
        [HttpPost]
        [Route("/asset-ids")]
        [ValidateModelState]
        [SwaggerOperation("FetchAssetMetadata")]
        [SwaggerResponse(statusCode: 200, type: typeof(Object), description: "Successful operation")]
        public virtual IActionResult FetchAssetMetadata([FromBody]Object body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Object));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 422 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(422);
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Object>(exampleJson)
                        : default(Object);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
