/*
 * ContentDistributionBackend
 *
 * Service providing content distribution metadata for ordered digital assets
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Threading.Tasks;
using DACM.ContentDistribution.Attributes;
using DACM.ContentDistribution.Models;
using DACM.ContentDistribution.Services;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;

namespace DACM.ContentDistribution.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DefaultApiController : ControllerBase
    {
        private readonly ContentDistributionMetadataService _contentDistributionMetadataService = new();
        
        /// <summary>
        /// Process order list and get the content distribution metadata
        /// </summary>
        /// <remarks>Process order list and get the content distribution metadata</remarks>
        /// <param name="body">Order list metadata</param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Invalid input</response>
        /// <response code="422">Validation exception</response>
        [HttpPost]
        [Route("/orderlist")]
        [ValidateModelState]
        [SwaggerOperation("ProcessOrderList")]
        [SwaggerResponse(statusCode: 200, type: typeof(ContentDistributionMetadata), description: "Successful operation")]
        public async Task<ObjectResult> ProcessOrderList([FromBody]OrderListMetadata body)
        {
            var contentDistributionMetadata = await _contentDistributionMetadataService.ProcessOrder(body);

            return new OkObjectResult(contentDistributionMetadata);
        }
    }
}
